import{a as f,S as y,i as d}from"./assets/vendor-Rdv7LHNr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();async function u({searchText:s,page:e,perPage:i}){return(await f.get("https://pixabay.com/api/",{params:{key:"45306533-f7c4428500ee3898e492b2a2f",page:e,per_page:i,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const L=document.querySelector("ul.js-gallery"),b=new y("ul.js-gallery a",{className:"js-lightbox",overlayOpacity:.8,captionsData:"alt",captionDelay:250});function h(s){const e=s.map(({webformatURL:i,largeImageURL:l,tags:t,likes:r,views:c,comments:g,downloads:p})=>`<li class="gallery-item">
	<a class="gallery-link" href="${l}">
		<img
			class="gallery-image"
			src="${i}"
			alt="${t}"
			/>
    <div class="image-stats">
  <p>Likes
${r}</p>
  <p> Views<br>${c}</p>
  <p>Comments<br>${g}</P>
  <p>Dowloads<br>${p}</P>
</div>
	</a>
</li>`).join("");L.insertAdjacentHTML("beforeend",e),b.refresh()}class w{constructor(e,i){this.buttonEL=e,this.hiddenClass=i}hide(){this.buttonEL.classList.add(this.hiddenClass)}show(){this.buttonEL.classList.remove(this.hiddenClass)}disable(){this.buttonEL.disabled=!0}enable(){this.buttonEL.disabled=!1}}const a={ulGallery:document.querySelector(".js-gallery"),searchForm:document.querySelector(".js-form"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),loader:document.querySelector(".loader")},n=new w(a.loadMoreBtn,"is-hidden");n.hide();a.searchForm.addEventListener("submit",v);const o={page:1,perPage:15,maxPages:0,searchText:"",orientation:"horizontal",safesearch:!0};async function v(s){if(s.preventDefault(),a.ulGallery.innerHTML="",o.page=1,a.loader.classList.remove("hidden"),n.hide(),o.searchText=s.currentTarget.elements.query.value.trim().toLowerCase(),o.searchText===""){a.loader.classList.add("hidden"),d.info({message:"The field cannot be empty!",position:"topRight",timeout:2e3}),s.currentTarget.reset();return}try{const e=await u(o);if(h(e.hits),e.hits.length===0){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,icon:""});return}o.maxPages=Math.ceil(e.totalHits/o.perPage),o.maxPages>1?(n.show(),a.loadMoreBtn.addEventListener("click",m)):n.hide()}catch(e){d.error({message:`Request failed with: ${e}`,position:"topRight",timeout:2e3})}finally{s.target.reset(),a.loader.classList.add("hidden")}}async function m(s){n.hide(),a.loader.classList.remove("hidden");try{const e=await u(o);h(e.hits),o.page+=1}catch(e){d.error({message:`Request failed with: ${e}`,position:"topRight",timeout:2e3})}finally{a.loader.classList.add("hidden");const e=document.querySelector(".js-gallery").getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"}),o.page===o.maxPages?(n.hide(),d.info({message:"We`re sorry, but you`ve reached the end of search results.",position:"topRight",timeout:2e3,icon:""}),a.loadMoreBtn.removeEventListener("click",m)):n.show()}}
//# sourceMappingURL=index.js.map
