import{a as f,S as y,i as d}from"./assets/vendor-Rdv7LHNr.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();async function u({searchText:t,page:r,perPage:i}){return(await f.get("https://pixabay.com/api/",{params:{key:"45306533-f7c4428500ee3898e492b2a2f",page:r,per_page:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const L=document.querySelector("ul.js-gallery"),b=new y("ul.js-gallery a",{className:"js-lightbox",overlayOpacity:.8,captionsData:"alt",captionDelay:250});function h(t){const r=t.map(({webformatURL:i,largeImageURL:l,tags:e,likes:s,views:c,comments:g,downloads:p})=>`<li class="gallery-item">
	<a class="gallery-link" href="${l}">
		<img
			class="gallery-image"
			src="${i}"
			alt="${e}"
			/>
    <div class="image-stats">
  <p>Likes
${s}</p>
  <p> Views<br>${c}</p>
  <p>Comments<br>${g}</P>
  <p>Dowloads<br>${p}</P>
</div>
	</a>
</li>`).join("");L.insertAdjacentHTML("beforeend",r),b.refresh()}class w{constructor(r,i){this.buttonEL=r,this.hiddenClass=i}hide(){this.buttonEL.classList.add(this.hiddenClass)}show(){this.buttonEL.classList.remove(this.hiddenClass)}disable(){this.buttonEL.disabled=!0}enable(){this.buttonEL.disabled=!1}}const a={ulGallery:document.querySelector(".js-gallery"),searchForm:document.querySelector(".js-form"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),loader:document.querySelector(".loader")},n=new w(a.loadMoreBtn,"is-hidden");n.hide();a.searchForm.addEventListener("submit",P);const o={page:1,perPage:15,maxPages:0,searchText:"",orientation:"horizontal",safesearch:!0};async function P(t){if(t.preventDefault(),a.ulGallery.innerHTML="",o.page=1,a.loader.classList.remove("hidden"),n.hide(),o.searchText=t.currentTarget.elements.query.value.trim().toLowerCase(),o.searchText===""){a.loader.classList.add("hidden"),d.info({message:"The field cannot be empty!",position:"topRight",timeout:2e3}),t.currentTarget.reset();return}try{const r=await u(o);if(h(r.hits),r.hits.length===0){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,icon:""});return}o.maxPages=Math.ceil(r.totalHits/o.perPage),o.maxPages>1?(n.show(),a.loadMoreBtn.addEventListener("click",m)):n.hide()}catch(r){d.error({message:`Request failed with: ${r}`,position:"topRight",timeout:2e3})}finally{t.target.reset(),a.loader.classList.add("hidden")}}async function m(){n.hide(),a.loader.classList.remove("hidden");try{const t=await u(o);h(t.hits),o.page+=1}catch(t){d.error({message:`Request failed with: ${t}`,position:"topRight",timeout:2e3})}finally{a.loader.classList.add("hidden");const t=document.querySelector(".js-gallery").getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"}),o.page===o.maxPages?(n.hide(),d.info({message:"We`re sorry, but you`ve reached the end of search results.",position:"topRight",timeout:2e3,icon:""}),a.loadMoreBtn.removeEventListener("click",m)):n.show()}}
//# sourceMappingURL=index.js.map
